### ISSUE TITLE
耗电严重

### ISSUE THREAD

**Issue by daxmu** [trojan-gfw/igniter#123]
常驻后台的话非常耗电，不像是简单的vpn应用应该消耗的电量

**Comment by oasiscifr** [comment]
All VPN applications use CPUs to copy data. I don't think it consumes more power than other applications, unless you provide test data compared with other applications. 

Testing should be performed on the premise that other applications have the application whitelist feature turned off.

**Comment by meepuru** [comment]
![Screenshot_20200907-092545](https://user-images.githubusercontent.com/30045376/92421644-34c1b380-f1ac-11ea-85b1-715ca9f46d99.png)
igniter(PID2548)
![Screenshot_20200908-080632](https://user-images.githubusercontent.com/30045376/92421646-38553a80-f1ac-11ea-9a3d-2640e5406171.png)
Clash(PID21185/PID21222)
使用同一节点，均为**空载**状态。

![Screenshot_20200908-083358](https://user-images.githubusercontent.com/30045376/92422074-4ad07380-f1ae-11ea-8e50-5c619a81599a.png)
Clash 测速时的资源占用(PID21222)

测试环境: Google Pixel3, Android10, termux+htop, 使用Magisk 获取 root 权限, Clash版本 2.1.5-arm64-v8a, igniter版本 0.9.9-beta.
如果从 htop 的显示来看，与 Clash 对比，igniter 存在占用资源较多的情况，并且在日常使用过程中确实发现设备电池寿命一定程度的降低，这或许是 igniter 本身所导致的问题。

我非常支持你们的项目，但如果确实是 igniter 存在性能问题，也愿请你们在以后的更新中能够改善 igniter 的性能。
感谢你们所做出的努力

**Comment by oasiscifr** [comment]
@meepuru Thanks for your analysis! It make sense. How did you config your clash? Did you turn on the app whitelist?

**Comment by meepuru** [comment]
I use a simple config like this:
```
port: 7890
socks-port: 7891
allow-lan: false
mode: Global
log-level: info

proxies:
- name: "*"
  type: trojan
  server: *
  port: 443
  password: *
  alpn:
     - h2
     - http/1.1
```

Anyway, Pixel devices don't have a app whitelist or something like that.
